# Generated by Django 3.2.7 on 2021-09-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210907_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='short_text',
            field=models.TextField(default='default text', max_length=150),
        ),
        migrations.AddField(
            model_name='update',
            name='update_slug',
            field=models.SlugField(default='random', max_length=100, unique=True),
        ),
    ]
