# Generated by Django 3.2.7 on 2021-09-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210908_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='short_text',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
