# Generated by Django 3.2.7 on 2021-09-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_update_slug_update_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='slug',
            new_name='update_slug',
        ),
    ]
