# Generated by Django 3.2.7 on 2021-09-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_slug_update_update_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
