# Generated by Django 3.2.7 on 2021-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_update_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_slug',
            field=models.SlugField(max_length=100),
        ),
    ]
