# Generated by Django 3.2.7 on 2021-09-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_update_update_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
