# Generated by Django 3.2.7 on 2021-09-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='picture',
            field=models.FileField(blank=True, default='media/default-2.jpg', upload_to='media/'),
        ),
    ]
