# Generated by Django 3.2.7 on 2021-09-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
