# Generated by Django 3.2.7 on 2021-09-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_price_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='description',
            field=models.CharField(default='desc', max_length=100),
        ),
    ]
