# Generated by Django 3.2.7 on 2021-10-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
