# Generated by Django 3.2.7 on 2021-10-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, default='media/default.jpg', upload_to='media/'),
        ),
    ]
