# Generated by Django 3.2.7 on 2021-10-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_stripepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_varieties',
        ),
        migrations.AddField(
            model_name='product',
            name='available_varieties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.varietyspec'),
        ),
    ]
