# Generated by Django 3.2.7 on 2021-10-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211023_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_varieties',
            field=models.ForeignKey(default='any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.varietyspec'),
        ),
    ]
