# Generated by Django 3.2.7 on 2021-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_available_varieties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_varieties',
        ),
        migrations.AddField(
            model_name='product',
            name='available_varieties',
            field=models.ManyToManyField(to='shop.VarietySpec'),
        ),
    ]
